trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'
  tags:
    include:
      - 'prod_*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install flask mysql-connector-python requests
  displayName: 'Instalar dependências'

- script: |
    python -m unittest discover -s tests
  displayName: 'Executar testes'

- script: |
    source venv/bin/activate
    export FLASK_APP=app.py
    flask run --host=0.0.0.0
  displayName: 'Iniciar aplicação Flask'
  env:
    FLASK_ENV: production