trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'
  tags:
    include:
      - 'prod_*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks that build, test, and deploy your project
    echo Use this section to run your project commands, like npm install, dotnet build, etc.
  displayName: 'Run multi-line script'